const VEHICLES = [
  {
    id: "car-swift",
    type: "car",
    name: "Maruti Swift",
    tag: "Hatchback",
    seats: 5,
    trans: "Manual",
    fuel: "Petrol",
    price: 1899,
    city: "Mumbai",
    img: "images/MARUTI.JPG"
  },
  {
    id: "car-city",
    type: "car",
    name: "Honda City",
    tag: "Sedan",
    seats: 5,
    trans: "Automatic",
    fuel: "Petrol",
    price: 2599,
    city: "Delhi",
    img: "https://images.unsplash.com/photo-1550355291-bbee04a92027?auto=format&fit=crop&w=1200&q=80"
  },
  {
    id: "car-innova",
    type: "car",
    name: "Toyota Innova Crysta",
    tag: "SUV",
    seats: 7,
    trans: "Automatic",
    fuel: "Diesel",
    price: 4299,
    city: "Bengaluru",
    img: "images/crysta.jpg"
  },
  {
    id: "car-thar",
    type: "car",
    name: "Mahindra Thar",
    tag: "Off-road",
    seats: 4,
    trans: "Manual",
    fuel: "Diesel",
    price: 3999,
    city: "Jaipur",
    img: "images/thar.jpg"
  },
  {
    id: "car-bmw",
    type: "car",
    name: "BMW 3 Series",
    tag: "Luxury",
    seats: 5,
    trans: "Automatic",
    fuel: "Petrol",
    price: 8999,
    city: "Mumbai",
    img: "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=80"
  },
  {
    id: "scooty-activa",
    type: "scooty",
    name: "Honda Activa 6G",
    tag: "Scooty",
    seats: 2,
    trans: "Automatic",
    fuel: "Petrol",
    price: 499,
    city: "Goa",
    img: "images/activa.jpg"
  },
  {
    id: "scooty-jupiter",
    type: "scooty",
    name: "TVS Jupiter",
    tag: "Scooty",
    seats: 2,
    trans: "Automatic",
    fuel: "Petrol",
    price: 449,
    city: "Pune",
    img: "images/jupiter.jpg"
  },
  {
    id: "scooty-ather",
    type: "scooty",
    name: "Ather 450X",
    tag: "Electric",
    seats: 2,
    trans: "Automatic",
    fuel: "Electric",
    price: 799,
    city: "Bengaluru",
    img: "images/ather.jpg"
  },
  {
    id: "scooty-vespa",
    type: "scooty",
    name: "Vespa SXL 150",
    tag: "Premium",
    seats: 2,
    trans: "Automatic",
    fuel: "Petrol",
    price: 899,
    city: "Goa",
    img: "images/vespa.jpg"
  },
  {
    id: "traveler-12",
    type: "traveler",
    name: "Force Traveller 12",
    tag: "Group",
    seats: 12,
    trans: "Manual",
    fuel: "Diesel",
    price: 6499,
    city: "Delhi",
    img: "https://images.unsplash.com/photo-1570125909232-eb263c188f7e?auto=format&fit=crop&w=1200&q=80"
  },
  {
    id: "traveler-17",
    type: "traveler",
    name: "Force Traveller 17",
    tag: "Tour",
    seats: 17,
    trans: "Manual",
    fuel: "Diesel",
    price: 7999,
    city: "Jaipur",
    img: "https://images.unsplash.com/photo-1570125909232-eb263c188f7e?auto=format&fit=crop&w=1200&q=80"
  },
  {
    id: "traveler-volvo",
    type: "traveler",
    name: "Volvo Mini Coach",
    tag: "Premium",
    seats: 21,
    trans: "Automatic",
    fuel: "Diesel",
    price: 12999,
    city: "Mumbai",
    img: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=1200&q=80"
  }
];
