create extension if not exists pgcrypto;

create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 2 and 100),
  email text not null,
  password_salt text not null,
  password_hash text not null,
  created_at timestamptz not null default now()
);
create unique index if not exists users_email_lower on public.users (lower(email));

create table if not exists public.sessions (
  token_hash text primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  expires_at timestamptz not null
);
create index if not exists sessions_expiry on public.sessions (expires_at);

create table if not exists public.bookings (
  id text primary key,
  user_id uuid not null references public.users(id),
  vehicle_id text not null,
  vehicle_name text not null,
  city text not null,
  start_date date not null,
  end_date date not null,
  days integer not null check (days between 1 and 30),
  driver boolean not null default false,
  helmet boolean not null default false,
  total integer not null check (total > 0),
  status text not null check (status in ('pending', 'confirmed', 'failed')),
  created_at timestamptz not null default now()
);
create index if not exists bookings_user_dates on public.bookings (user_id, end_date);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id),
  booking_id text not null references public.bookings(id),
  gateway_order_id text not null unique,
  gateway_payment_id text unique,
  amount integer not null check (amount > 0),
  currency text not null default 'INR',
  status text not null check (status in ('pending', 'paid', 'failed')),
  created_at timestamptz not null default now(),
  paid_at timestamptz
);
create index if not exists payments_user_date on public.payments (user_id, created_at desc);

alter table public.users enable row level security;
alter table public.sessions enable row level security;
alter table public.bookings enable row level security;
alter table public.payments enable row level security;